language: node_js
node_js:
  - "7"
  
before_script:
  - npm install
  
script:
  - echo "Antes de la construcción"
  - npm build

deploy:
  provider: pages
  local-dir: build/
  skip_cleanup: true
  github_token:  c60430c9f0a65a07ce482e3ac49d4f7ccb2ec7a2
  keep_history: true
  on:
    branch: master
